language: php
sudo: false

php:
    - 5.6
    - 7.1

matrix:
    allow_failures:
        - php: 7.1

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then
        phpenv config-rm xdebug.ini;
      fi;
    - echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
    - composer self-update --no-interaction
    - composer update --no-interaction --no-scripts --prefer-dist

script:
    - ./bin/phpspec run
